# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'LectureBuddy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LectureBuddy

  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Firestore'
  pod 'FirebaseUI', '~> 4.0'

  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'

  pod 'NVActivityIndicatorView'
  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'
  pod 'Tabman', '~> 1.0'

  target 'LectureBuddyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LectureBuddyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
