# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LectureBuddy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LectureBuddy

  pod 'Firebase/Core'

  target 'LectureBuddyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LectureBuddyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
